"""RunPlan — structured (not verbatim) livestream host plan.

Generated by POST /sessions/{id}/plan/create. Director uses phases +
key_selling_points as the proactive cursor driver. Anticipated FAQs deferred P2.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class SellingTask(BaseModel):
    stage: Literal["intro", "benefit", "offer", "trust", "cta", "transition"]
    task_id: str
    instruction: str


class OpeningPhase(BaseModel):
    intro_shop: str = "Chào mừng cả nhà đến livestream!"
    persona: str = "MC bán hàng nhiệt tình"
    pull_view: str = "Ai mới vào thì like + follow ủng hộ shop nhé!"
    call_to_share: str = "Share live cho bạn bè cùng săn deal!"


class ClosingPhase(BaseModel):
    thanks: str = "Cảm ơn cả nhà đã xem live!"
    follow_cta: str = "Follow shop để không bỏ lỡ deal tiếp theo."
    teaser_next: str = "Live sau còn deal sốc hơn — hẹn gặp lại!"


class ProductSellingPhase(BaseModel):
    product_id: str
    product_name: str = ""
    key_selling_points: list[str] = Field(default_factory=list)
    tasks: list[SellingTask] = Field(default_factory=list)
    min_duration_sec: int = 120
    max_duration_sec: int = 480
    transition_cue: str = "Chuyển sang sản phẩm tiếp theo nhé!"
    # P2: anticipated_faqs: list[str] = []


class RunPlan(BaseModel):
    """Structured run plan: opening → selling(product_i)* → closing."""

    phases: list[Literal["opening", "selling", "closing"]] = Field(
        default_factory=lambda: ["opening", "closing"]
    )
    opening: OpeningPhase = Field(default_factory=OpeningPhase)
    selling: list[ProductSellingPhase] = Field(default_factory=list)
    closing: ClosingPhase = Field(default_factory=ClosingPhase)
    persona: Optional[str] = None
