"""Tenant-scoped voice profile metadata (Change T tasks 4.1/5.2).

Metadata is provider-neutral and never carries provider payloads (speaker
embeddings, reference codes). Payloads live behind ``provider_payload_location``
and are resolved through the store — the profile object stays small enough for
the LRU cache and safe to serialize in API responses.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Literal
from uuid import uuid4

ProfileKind = Literal["preset", "cloned"]


def new_voice_profile_id() -> str:
    """Return a fresh opaque profile id (e.g. ``vp_<hex>``)."""
    return f"vp_{uuid4().hex}"


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


@dataclass(frozen=True)
class VoiceProfile:
    """Opaque, tenant-scoped metadata for one preset or cloned voice.

    The id is generated by the store/service — callers never choose it, so a
    display-name collision across tenants stays harmless.
    """

    voice_profile_id: str
    tenant_id: str
    provider_name: str
    provider_model_revision: str
    profile_kind: ProfileKind
    display_name: str
    provider_payload_location: str
    created_at: datetime = _now_utc()
